/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.persa.view;

import co.edu.sena.persa.controllers.CareerController;
import co.edu.sena.persa.controllers.CourseController;
import co.edu.sena.persa.controllers.ICareerController;
import co.edu.sena.persa.controllers.ICourseController;
import co.edu.sena.persa.model.Career;
import co.edu.sena.persa.model.Course;
import co.edu.sena.persa.utils.MessageUtils;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebas
 */
public class JFrameCourses extends javax.swing.JFrame {
    private ICourseController courseController = new CourseController();
    private ICareerController careerController = new CareerController();

    /**
     * Creates new form JFrameCourses
     */
    public JFrameCourses() {
        initComponents();
        fillCombos();
        fillTable();
    }
    
    public void fillCombos()
    {
        try {
            
            List<Career> career = careerController.findAll();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            jComboBoxCareer.setModel(model);
            model.addAll(career);
            
        } catch (Exception e) {
            MessageUtils.ShowErrorMessage(e.getMessage());
        }
            
    }
    
    public void fillTable()
    {
        try {
            DefaultTableModel model = new DefaultTableModel();
            jTableCourses.setModel(model);
            model.addColumn("Id");
            model.addColumn("Programa");
            model.addColumn("Trimestre");
            model.addColumn("Jornada");
            model.addColumn("Estado");
            model.addColumn("Año");
            
            String [] rows = new String[6];
            List<Course> course = courseController.findAll();
            for (Course c : course) {
                rows[0] = String.valueOf(c.getId());
                rows[1] = c.getCareerId().getName();
                rows[2] = c.getTrimester();
                rows[3] = c.getShift();
                rows[4] = c.getStatus();
                rows[5] = c.getYear();
                
                model.addRow(rows);
            }
        } catch (Exception e) {
            MessageUtils.ShowErrorMessage(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBody = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelIconSena = new javax.swing.JLabel();
        jLabelIconPersa = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCourses = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClean = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelHome = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelTrimester = new javax.swing.JLabel();
        jComboBoxTrimester = new javax.swing.JComboBox<>();
        jLabelStatus = new javax.swing.JLabel();
        jLabelCareer = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jLabelShift = new javax.swing.JLabel();
        jComboBoxShift = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jComboBoxCareer = new javax.swing.JComboBox<>();
        jTextFieldYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("COURSES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBody.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(0, 48, 77));

        jLabelIconSena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSenaR.png"))); // NOI18N

        jLabelIconPersa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSenaX.png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("CURSOS");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(jLabelIconSena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(197, 197, 197)
                .addComponent(jLabelIconPersa)
                .addGap(24, 24, 24))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelIconSena)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelIconPersa)))
        );

        jPanelBody.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 785, -1));

        jTableCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCourses);

        jPanelBody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 292, 785, 201));

        jButtonAdd.setBackground(new java.awt.Color(57, 169, 0));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addWhite.png"))); // NOI18N
        jButtonAdd.setText("CREAR");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanelBody.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 251, -1, -1));

        jButtonUpdate.setBackground(new java.awt.Color(51, 51, 255));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editWhite.png"))); // NOI18N
        jButtonUpdate.setText("ACTUALIZAR");
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanelBody.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 251, -1, -1));

        jButtonClean.setBackground(new java.awt.Color(255, 255, 153));
        jButtonClean.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonClean.setForeground(new java.awt.Color(0, 0, 0));
        jButtonClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cleanBlack.png"))); // NOI18N
        jButtonClean.setText("LIMPIAR");
        jButtonClean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });
        jPanelBody.add(jButtonClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 251, -1, -1));

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteWhite.png"))); // NOI18N
        jButtonDelete.setText("ELIMINAR");
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanelBody.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 251, -1, -1));

        jLabelHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeBlack.png"))); // NOI18N
        jLabelHome.setText("MENU");
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });
        jPanelBody.add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        jLabelId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(0, 0, 0));
        jLabelId.setText("Id: ");
        jPanelBody.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 31, -1));

        jTextFieldId.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldId.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBody.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 122, 164, -1));

        jLabelTrimester.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTrimester.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTrimester.setText("Trimestre:");
        jPanelBody.add(jLabelTrimester, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 120, -1, -1));

        jComboBoxTrimester.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxTrimester.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxTrimester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion...", "T1 ", "T2", "T3", "T4" }));
        jComboBoxTrimester.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxTrimester.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBody.add(jComboBoxTrimester, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 120, 152, -1));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStatus.setText("Estado:");
        jPanelBody.add(jLabelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 120, -1, -1));

        jLabelCareer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCareer.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCareer.setText("Programa:");
        jPanelBody.add(jLabelCareer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, -1, -1));

        jLabelYear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelYear.setForeground(new java.awt.Color(0, 0, 0));
        jLabelYear.setText("Año:");
        jPanelBody.add(jLabelYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 184, 37, -1));

        jLabelShift.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelShift.setForeground(new java.awt.Color(0, 0, 0));
        jLabelShift.setText("Jornada:");
        jPanelBody.add(jLabelShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 184, -1, -1));

        jComboBoxShift.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxShift.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion...", "DIURNA ", "NOCTURNA ", "MIXTA" }));
        jComboBoxShift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxShift.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBody.add(jComboBoxShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 184, 152, -1));

        jComboBoxStatus.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxStatus.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion...", "ACTIVO", "INACTIVO" }));
        jComboBoxStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBody.add(jComboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 120, 174, -1));

        jComboBoxCareer.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCareer.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCareer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxCareer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBody.add(jComboBoxCareer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 184, 164, -1));

        jTextFieldYear.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldYear.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBody.add(jTextFieldYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 186, 174, -1));

        getContentPane().add(jPanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        JFrameHome home = new JFrameHome();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jTableCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCoursesMouseClicked
        int rowSelected = jTableCourses.getSelectedRow();
        if(rowSelected != -1)
        {
            long idSelected = Long.parseLong(jTableCourses.getValueAt(rowSelected, 0).toString());
            try {
                Course c = courseController.findById(idSelected);
                jTextFieldId.setText(String.valueOf(idSelected));
                jTextFieldYear.setText(c.getYear());
                jComboBoxCareer.getModel().setSelectedItem(c.getCareerId().getName());
                jComboBoxStatus.getModel().setSelectedItem(c.getStatus());
                jComboBoxShift.getModel().setSelectedItem(c.getShift());
                jComboBoxTrimester.getModel().setSelectedItem(c.getTrimester());

                jButtonAdd.setEnabled(false);
                jButtonUpdate.setEnabled(true);
                jButtonDelete.setEnabled(true);
            } catch (Exception e) {
                MessageUtils.ShowInfoMessage(e.getMessage());
            }
            } 
    }//GEN-LAST:event_jTableCoursesMouseClicked

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
       clean();
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        try {
            Course course = new Course();
            course.setId(Long.parseLong(jTextFieldId.getText()));
            course.setStatus(jComboBoxStatus.getSelectedItem().toString());
            course.setTrimester(jComboBoxTrimester.getSelectedItem().toString());
            course.setShift(jComboBoxShift.getSelectedItem().toString());
            course.setYear(jTextFieldYear.getText());
            
            Career career = (Career) jComboBoxCareer.getSelectedItem();
            course.setCareerId(career);
            
            courseController.insert(course);
            MessageUtils.ShowInfoMessage("El curso creado exitosamente");
            fillTable();
            clean();
            
        } catch (Exception e) {
            MessageUtils.ShowErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            Course course = new Course();
            course.setId(Long.parseLong(jTextFieldId.getText()));
            course.setStatus(jComboBoxStatus.getSelectedItem().toString());
            course.setTrimester(jComboBoxTrimester.getSelectedItem().toString());
            course.setShift(jComboBoxShift.getSelectedItem().toString());
            course.setYear(jTextFieldYear.getText());
            
            Career career = (Career) jComboBoxCareer.getSelectedItem();
            course.setCareerId(career);
           
            courseController.update(course);
            MessageUtils.ShowInfoMessage("El curso fue actualizado exitosamente");
            fillTable();
            clean();
            
        } catch (Exception e) {
            MessageUtils.ShowErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            int option = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de eliminar el registro?", 
                         "Confirmacion", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION)
            {
                courseController.delete(Long.parseLong(jTextFieldId.getText()));
                MessageUtils.ShowInfoMessage("El curso fue eliminado exitosamente");
                fillTable();
            }
            clean();
        } catch (Exception e) {
            MessageUtils.ShowErrorMessage(e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    
    public void clean()
    {
        jTextFieldId.setText("");
        jTextFieldYear.setText("");
        jComboBoxCareer.setSelectedIndex(0);
        jComboBoxStatus.setSelectedIndex(0);
        jTableCourses.clearSelection();
        jComboBoxShift.setSelectedIndex(0);
        jComboBoxTrimester.setSelectedIndex(0);
        jButtonAdd.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxCareer;
    private javax.swing.JComboBox<String> jComboBoxShift;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxTrimester;
    private javax.swing.JLabel jLabelCareer;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelIconPersa;
    private javax.swing.JLabel jLabelIconSena;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelShift;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTrimester;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCourses;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
