/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.persa.view;

/**
 * Fecha: 24/04/2025
 * @author Aprendices: Juan Sebastian Rodriguez Cruz
 *                                     Lina Vanessa Salcedo Cuellar
 *                                     Manuel Alejandro Ocampo Saya
 * Obejtivo: Diseño de los JFrames del proyecto PERSA
 */
public class JFrameApprenticeCourse extends javax.swing.JFrame {

    /**
     * Creates new form JFrameApprenticeCourse
     */
    public JFrameApprenticeCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelApprenticeCourse = new javax.swing.JPanel();
        jLabelHomeIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelApprenticeCourse.setBackground(new java.awt.Color(0, 204, 102));

        jLabelHomeIcon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelHomeIcon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHomeIcon.setIcon(new javax.swing.ImageIcon("D:\\repos\\TallerJPA\\TallerJPA\\resources\\home.png")); // NOI18N
        jLabelHomeIcon.setText("HOME");
        jLabelHomeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHomeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelApprenticeCourseLayout = new javax.swing.GroupLayout(jPanelApprenticeCourse);
        jPanelApprenticeCourse.setLayout(jPanelApprenticeCourseLayout);
        jPanelApprenticeCourseLayout.setHorizontalGroup(
            jPanelApprenticeCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApprenticeCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHomeIcon)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanelApprenticeCourseLayout.setVerticalGroup(
            jPanelApprenticeCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApprenticeCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHomeIcon)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelApprenticeCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelApprenticeCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHomeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeIconMouseClicked
        JFrameHome home = new JFrameHome();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelHomeIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameApprenticeCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameApprenticeCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameApprenticeCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameApprenticeCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameApprenticeCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelHomeIcon;
    private javax.swing.JPanel jPanelApprenticeCourse;
    // End of variables declaration//GEN-END:variables
}
