<<<<<<< HEAD
=======
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.persa.view;

import javax.swing.ImageIcon;

/**
 *
 * @author Sebas
 */
public class JFrameHome extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonCareer = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonCourse = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanelSection = new javax.swing.JPanel();
        jLabelIconPersa = new javax.swing.JLabel();
        jLabelIconSena = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("HOME");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCareer.setBackground(new java.awt.Color(57, 169, 0));
        jButtonCareer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCareer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCareer.setText("CARRERAS");
        jButtonCareer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCareerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCareer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 160, 30));

        jButtonExit.setBackground(new java.awt.Color(255, 0, 0));
        jButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jButtonExit.setText("SALIR");
        jButtonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, 100, 30));

        jButtonCourse.setBackground(new java.awt.Color(57, 169, 0));
        jButtonCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCourse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCourse.setText("CURSOS");
        jButtonCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCourseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, 30));

        jLabelTitle.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitle.setText("PAGINA PRINCIPAL");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanelBody.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 310));

        jPanelSection.setBackground(new java.awt.Color(0, 48, 77));

        jLabelIconPersa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSenaX.png"))); // NOI18N

        jLabelIconSena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSenaR.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSectionLayout = new javax.swing.GroupLayout(jPanelSection);
        jPanelSection.setLayout(jPanelSectionLayout);
        jPanelSectionLayout.setHorizontalGroup(
            jPanelSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSectionLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabelIconPersa)
                .addGap(15, 15, 15))
            .addGroup(jPanelSectionLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelIconSena)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSectionLayout.setVerticalGroup(
            jPanelSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSectionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelIconSena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jLabelIconPersa)
                .addContainerGap())
        );

        getContentPane().add(jPanelSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 150, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCareerActionPerformed
        JFrameCareer career = new JFrameCareer();
        career.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCareerActionPerformed

    private void jButtonCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCourseActionPerformed
        JFrameCourses course = new JFrameCourses();
        course.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCourseActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCareer;
    private javax.swing.JButton jButtonCourse;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelIconPersa;
    private javax.swing.JLabel jLabelIconSena;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelSection;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
>>>>>>> origin/dev
